In [23]:
import numpy as np

In [22]:
# Number 4.1 Create a 3x3 NumPy array with values ranging from 1 to 9.
new_array = np.arange(1, 10).reshape(3, 3)

print("Original 3x3 Array:")
print(new_array)

Original 3x3 Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
# Number 4.2 Find the sum, mean, and standard deviation of the array.
new_array_sum = np.sum(new_array)
new_array_mean = np.mean(new_array)
new_array_std = np.std(new_array)

print("Sum of the array:", new_array_sum)
print("Mean of the array:", new_array_mean)
print("Standard deviation of the array:", new_array_std)

Sum of the array: 45
Mean of the array: 5.0
Standard deviation of the array: 2.581988897471611


In [26]:
# Number 4.3 Extract the subarray consisting of the first two rows and first two columns
subarray = new_array[:2, :2]

print("Subarray consisting first two rows and first two columns:")
print(subarray)

Subarray consisting first two rows and first two columns:
[[1 2]
 [4 5]]
